---
abstract: 'WebIDF calculator'
author:
  - 'pawa <pawapawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0.98
  Test::Requires: 0
  Test::TCP: 1.15
  Test::Warn: 0.2
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-WebIDF
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Furl::HTTP: 0
  Module::Load: 0.22
  Storable: 0
  URI: 0
  perl: 5.8.1
resources:
  bugtracker: https://github.com/pawa-/Lingua-JA-WebIDF/issues
  license: http://dev.perl.org/licenses
  repository: https://github.com/pawa-/Lingua-JA-WebIDF
version: 0.40
